on:
  push:
    branches:
      - main  # Ensure this matches the branch you want to trigger the workflow on

jobs:
  terraform-cd:
    runs-on: ubuntu-latest

    steps:
    #Terraform Apply
    - name: Terraform Apply
      run: terraform apply --auto-approve
    # - name: Export terraform outputs
    #   id: tfout
    #   run: |
    #     echo "EB_APP=$(terraform output -raw app_name)" >> $GITHUB_OUTPUT
    #     echo "EB_ENV=$(terraform output -raw env_name)" >> $GITHUB_OUTPUT

    # - name: Generate deployment package
    #   working-directory: ./nodejs
    #   run: zip -r ../deploy.zip .

    # - name: Deploy to EB
    #   uses: einaregilsson/beanstalk-deploy@v22
    #   with:
    #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     application_name: ${{ steps.tfout.outputs.EB_APP }}
    #     environment_name: ${{ steps.tfout.outputs.EB_ENV }}
    #     version_label: ${{ github.sha }}
    #     region: ${{ env.AWS_REGION }}
    #     deployment_package: deploy.zip