name: Terraform CI

on: push

env:            
  AWS_REGION: ap-southeast-1 

jobs:
  Terraform-ci:
    runs-on: ubuntu-latest

    steps:
    #setup
    - name: Checkout repository
      uses: actions/checkout@v2
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    #install terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    #terraform init 
    - name: Terraform Init
      run: terraform init
   
    #terraform fmt
    - name: Terraform prettify
      run: terraform fmt --recursive

    #terraform validate
    - name: Terraform Validate
      run: terraform validate

    - uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: latest
    
    - name: Show version
      run: tflint --version


    - name: Init TFLint
      run: tflint --init


    - name: Run


    #terraform plan
    - name: Terraform Plan
      run: terraform plan --var-file=environments/prod.tfvars
   